### ISSUE TITLE
Add GitHub Actions continuous integration

### ISSUE THREAD

**Issue by FreddyWordingham** [UniExeterRSE/WebApp#4]
Create a `WebApp/.github` directory, and then a `WebApp/.github/workflows` directory within that.

Within this folder create a `ci.yml` file containing our continuous integration script:

```yml
name: CI

on: [pull_request, push]

jobs:
    test:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Update pip
              run: |
                  python -m ensurepip
                  python -m pip install --upgrade pip

            - name: Configure poetry
              run: |
                  python -m pip install poetry
                  python -m poetry config virtualenvs.in-project true
                  python -m poetry config virtualenvs.create true

            - name: Set up cache
              uses: actions/cache@v2
              id: cache
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/pyproject.toml') }}

            - name: Install Package
              run: python -m poetry install

            - name: Quality Assurance
              run: |
                  poetry run flake8 ./my_library/ --count --select=E9,F63,F7,F82, --ignore=F821 --show-source --statistics
                  poetry run flake8 ./tests/ --count --select=E9,F63,F7,F82, --ignore=F821 --show-source --statistics
                  poetry run black --diff ./my_library/
                  poetry run black --diff ./tests/

            - name: Testing
              run: poetry run pytest --cache-clear --cov=my_library ./tests/
```
